import { motion } from 'motion/react';
import { useLocale } from '../context/LocaleContext';
import Footer from '../components/Footer';
import { Shield, Lock, Eye, FileText, Mail, ChevronRight } from 'lucide-react';

const standardTransition = { duration: 0.6, ease: [0.22, 1, 0.36, 1] };

export default function Privacy() {
  const { locale } = useLocale();

  const idContent = {
    title: "Kebijakan Privasi",
    subtitle: "Bagaimana kami menjaga kerahasiaan & keamanan ide startup Anda di Convix.",
    lastUpdated: "Terakhir diperbarui: 21 Mei 2026",
    intro: "Di Convix Idea Lab, kami memahami bahwa ide startup Anda adalah aset yang sangat berharga. Kami berkomitmen penuh untuk melindungi privasi ide, data, dan file analisis Anda dengan standar keamanan kelas industri.",
    sections: [
      {
        icon: <Shield className="w-5 h-5 text-[#ef4d23]" />,
        title: "1. Perlindungan Hak Kekayaan Intelektual",
        text: "Semua ide bisnis, target pasar, dokumen, dan audio yang Anda unggah ke platform Convix sepenuhnya merupakan hak milik intelektual Anda. Kami tidak akan pernah mengklaim kepemilikan, membagikan, atau menjual ide bisnis Anda kepada kompetitor atau pihak ketiga mana pun. Semua analisis yang dihasilkan oleh mesin AI kami bersifat privat dan hanya dapat diakses oleh akun Anda."
      },
      {
        icon: <Eye className="w-5 h-5 text-[#ef4d23]" />,
        title: "2. Data yang Kami Kumpulkan",
        text: "Kami mengumpulkan informasi yang minimal untuk menyediakan fungsionalitas terbaik: (a) Informasi akun: Alamat email dan nama dari integrasi pihak ketiga (Google/GitHub) atau Magic Link. (b) Data Masukan Analisis: Teks deskripsi ide, file lampiran riset, dan rekaman suara yang diunggah untuk transkripsi. (c) Hasil Analisis: Laporan SWOT, peta kompetisi, analisis kelayakan, dan dokumen ekspor yang dihasilkan."
      },
      {
        icon: <Lock className="w-5 h-5 text-[#ef4d23]" />,
        title: "3. Keamanan Informasi & Infrastruktur",
        text: "Infrastruktur kami dibangun di atas database terenkripsi Supabase PostgreSQL. Kami menerapkan Row Level Security (RLS) yang sangat ketat untuk memastikan bahwa data Anda tidak pernah bocor atau diakses oleh pengguna lain. Seluruh transmisi data dienkripsi menggunakan protokol HTTPS/TLS 1.3 standar industri."
      },
      {
        icon: <FileText className="w-5 h-5 text-[#ef4d23]" />,
        title: "4. Penggunaan Layanan Pihak Ketiga",
        text: "Untuk menyediakan validasi ide dan pencarian otomatis berkecepatan tinggi, kami berinteraksi dengan API OpenAI, OpenRouter, Gemini API, dan Tavily Search Engine secara aman. Data yang dikirim ke API ini bersifat anonim dan tidak mencakup data pribadi Anda, melainkan hanya konteks bisnis yang Anda kirimkan untuk divalidasi secara objektif."
      }
    ],
    contactTitle: "Pertanyaan & Dukungan",
    contactText: "Jika Anda memiliki kekhawatiran atau pertanyaan terkait kebijakan privasi kami, silakan hubungi tim keamanan kami di:",
    footerText: "Terima kasih telah mempercayakan ide masa depan Anda di Convix Idea Lab."
  };

  const enContent = {
    title: "Privacy Policy",
    subtitle: "How we protect the confidentiality and security of your startup ideas at Convix.",
    lastUpdated: "Last updated: May 21, 2026",
    intro: "At Convix Idea Lab, we understand that your startup ideas are highly valuable assets. We are fully committed to protecting the privacy of your ideas, data, and analytical files using industry-standard security models.",
    sections: [
      {
        icon: <Shield className="w-5 h-5 text-[#ef4d23]" />,
        title: "1. Intellectual Property Protection",
        text: "All business ideas, target markets, documents, and audio tracks that you submit to the Convix platform remain entirely your intellectual property. We will never claim ownership, distribute, or sell your business models to competitors or any third parties. All evaluations generated by our AI core are private and strictly accessible by your account only."
      },
      {
        icon: <Eye className="w-5 h-5 text-[#ef4d23]" />,
        title: "2. Data We Collect",
        text: "We collect minimal information required to offer top-tier validation services: (a) Account Information: Email addresses and profile names through authentication providers (Google/GitHub) or Magic Links. (b) Analysis Inputs: Written idea drafts, research uploads, and voice recordings submitted for audio transcribing. (c) Generated Analytics: SWOT matrices, regulatory audits, and downloaded export documents."
      },
      {
        icon: <Lock className="w-5 h-5 text-[#ef4d23]" />,
        title: "3. Information Security & Infrastructure",
        text: "Our entire workspace is built on Supabase encrypted PostgreSQL database clusters. We deploy strict Row Level Security (RLS) models guaranteeing that your data is never exposed to other clients. All network data transfers are fully secured using enterprise-grade HTTPS/TLS 1.3 encryption protocols."
      },
      {
        icon: <FileText className="w-5 h-5 text-[#ef4d23]" />,
        title: "4. Third-Party Integrations",
        text: "To execute real-time validations and autonomous web lookups, we interact securely with OpenAI, OpenRouter, Google Gemini API, and Tavily Search Engine APIs. Inputs shared with these gateways are fully anonymous and contain no user identity markers, sending only the raw business context required for automated audits."
      }
    ],
    contactTitle: "Inquiries & Support",
    contactText: "If you have any questions or security concerns regarding our privacy policies, feel free to contact our engineering team at:",
    footerText: "Thank you for trusting your future-shaping business strategies with Convix Idea Lab."
  };

  const t = locale === 'id' ? idContent : enContent;

  return (
    <div className="min-h-screen flex flex-col theme-transition" style={{ backgroundColor: 'var(--bg)', color: 'var(--fg)' }}>
      {/* ===== Header Hero Section ===== */}
      <section className="relative overflow-hidden pt-36 pb-20 border-b theme-transition" style={{ borderColor: 'var(--border)' }}>
        <div className="absolute inset-0 pointer-events-none opacity-20">
          <div className="absolute top-0 left-1/4 w-[1px] h-full theme-transition" style={{ backgroundColor: 'var(--border)' }} />
          <div className="absolute top-0 left-3/4 w-[1px] h-full theme-transition" style={{ backgroundColor: 'var(--border)' }} />
        </div>

        <div className="max-w-4xl mx-auto px-6 relative z-10 text-center">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={standardTransition}
          >
            <span className="text-[11px] font-mono font-bold tracking-widest text-[#ef4d23] bg-[#ef4d23]/[0.06] px-3 py-1.5 rounded-full border border-[#ef4d23]/10 uppercase mb-4 inline-block">
              Security & Privacy
            </span>
            <h1 className="text-3xl md:text-5xl font-medium tracking-tight mb-4 text-center theme-transition" style={{ color: 'var(--fg)' }}>
              {t.title}
            </h1>
            <p className="text-sm md:text-base leading-relaxed max-w-xl mx-auto theme-transition" style={{ color: 'var(--fg-secondary)' }}>
              {t.subtitle}
            </p>
            <span className="text-[11px] font-mono block mt-4 theme-transition" style={{ color: 'var(--fg-muted)' }}>
              {t.lastUpdated}
            </span>
          </motion.div>
        </div>
      </section>

      {/* ===== Policy Core Content ===== */}
      <section className="py-20 flex-1 theme-transition">
        <div className="max-w-3xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={standardTransition}
            className="mb-16 p-6 rounded-2xl border text-sm leading-relaxed theme-transition"
            style={{ backgroundColor: 'var(--bg-card)', borderColor: 'var(--border)' }}
          >
            <p className="theme-transition" style={{ color: 'var(--fg-secondary)' }}>{t.intro}</p>
          </motion.div>

          <div className="space-y-12">
            {t.sections.map((section, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: idx * 0.08 }}
                className="flex gap-5"
              >
                <div className="w-10 h-10 rounded-xl bg-[#ef4d23]/10 border border-[#ef4d23]/20 flex items-center justify-center shrink-0 mt-0.5">
                  {section.icon}
                </div>
                <div>
                  <h3 className="text-lg font-bold mb-3 theme-transition" style={{ color: 'var(--fg)' }}>{section.title}</h3>
                  <p className="text-[14px] leading-relaxed theme-transition" style={{ color: 'var(--fg-secondary)' }}>{section.text}</p>
                </div>
              </motion.div>
            ))}
          </div>

          {/* ===== Contact Block ===== */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={standardTransition}
            className="mt-20 p-8 rounded-3xl border text-center theme-transition"
            style={{ backgroundColor: 'var(--bg-elevated)', borderColor: 'var(--border)' }}
          >
            <h3 className="text-xl font-bold mb-3 theme-transition" style={{ color: 'var(--fg)' }}>{t.contactTitle}</h3>
            <p className="text-sm leading-relaxed mb-6 max-w-lg mx-auto theme-transition" style={{ color: 'var(--fg-secondary)' }}>
              {t.contactText}
            </p>
            <a
              href="mailto:arieffajarmarhas@gmail.com"
              className="inline-flex items-center gap-2 bg-[#ef4d23] text-white font-semibold text-sm px-6 py-3 rounded-full hover:bg-[#d9441f] transition-colors"
            >
              <Mail size={16} />
              arieffajarmarhas@gmail.com
            </a>
          </motion.div>

          <p className="text-center text-xs mt-16 theme-transition" style={{ color: 'var(--fg-muted)' }}>
            {t.footerText}
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
}
