import { motion } from 'motion/react';
import { useLocale } from '../context/LocaleContext';
import Footer from '../components/Footer';
import { Shield, Hammer, AlertTriangle, HelpCircle, Mail } from 'lucide-react';

const standardTransition = { duration: 0.6, ease: [0.22, 1, 0.36, 1] };

export default function Terms() {
  const { locale } = useLocale();

  const idContent = {
    title: "Ketentuan Layanan",
    subtitle: "Aturan dan panduan penggunaan platform Convix Idea Lab.",
    lastUpdated: "Terakhir diperbarui: 21 Mei 2026",
    intro: "Selamat datang di Convix Idea Lab. Ketentuan Layanan ini mengatur penggunaan Anda terhadap situs web, aplikasi, dan platform kecerdasan buatan kami. Dengan mengakses platform kami, Anda setuju untuk terikat oleh ketentuan ini.",
    sections: [
      {
        icon: <Shield className="w-5 h-5 text-[#ef4d23]" />,
        title: "1. Penggunaan Layanan & Akun",
        text: "Anda wajib mendaftar menggunakan email aktif atau integrasi akun Google/GitHub untuk mengakses platform. Anda bertanggung jawab penuh atas keamanan kredensial akun Anda. Penggunaan platform dibatasi untuk tujuan validasi ide bisnis, strategi startup, riset pasar, dan analisis terkait."
      },
      {
        icon: <Hammer className="w-5 h-5 text-[#ef4d23]" />,
        title: "2. Batasan Penggunaan (Prohibited Conduct)",
        text: "Anda dilarang keras untuk: (a) Mengeksploitasi celah keamanan API atau melakukan reverse-engineering terhadap model AI kami. (b) Menggunakan bot otomatis secara berlebihan untuk melakukan spamming API. (c) Mengunggah file berbahaya yang berisi virus, malware, atau trojan. (d) Memanipulasi platform untuk tindakan ilegal atau melanggar hukum setempat."
      },
      {
        icon: <AlertTriangle className="w-5 h-5 text-[#ef4d23]" />,
        title: "3. Penafian & Batasan Tanggung Jawab (Disclaimer)",
        text: "Seluruh hasil analisis, prediksi kegagalan, analisis SWOT, dan kalkulasi pasar yang dihasilkan oleh Convix AI didasarkan pada model probabilitas statistik dan informasi publik secara real-time. Hasil analisis ini bersifat sebagai panduan pengambilan keputusan strategis dan tidak boleh ditafsirkan sebagai saran hukum atau keuangan mutlak. Segala keputusan bisnis dan investasi akhir sepenuhnya merupakan tanggung jawab Anda sebagai founder."
      },
      {
        icon: <HelpCircle className="w-5 h-5 text-[#ef4d23]" />,
        title: "4. Kebijakan Berlangganan & Pengembalian",
        text: "Beberapa fitur premium seperti analisis deep-diving berkapasitas tinggi memerlukan langganan berbayar. Anda dapat membatalkan langganan Anda kapan saja melalui dashboard pengaturan billing Anda. Pembayaran yang telah diproses tidak dapat dikembalikan secara retrospektif kecuali diwajibkan oleh hukum setempat."
      }
    ],
    contactTitle: "Hubungi Kami",
    contactText: "Jika Anda memiliki pertanyaan seputar Ketentuan Layanan ini, silakan hubungi tim legalitas kami di:",
    footerText: "Terima kasih telah membangun masa depan bisnis Anda bersama Convix Idea Lab."
  };

  const enContent = {
    title: "Terms of Service",
    subtitle: "Rules, guidelines, and terms governing your use of Convix Idea Lab.",
    lastUpdated: "Last updated: May 21, 2026",
    intro: "Welcome to Convix Idea Lab. These Terms of Service govern your access to and use of our website, applications, and artificial intelligence validation platforms. By entering our site, you agree to be bound by these terms.",
    sections: [
      {
        icon: <Shield className="w-5 h-5 text-[#ef4d23]" />,
        title: "1. Service Access & Accounts",
        text: "You must authenticate using an active email or OAuth (Google/GitHub) integrations. You are fully responsible for maintaining the privacy of your account. Platform usage is strictly designated for business validation, competitive mapping, and early-stage strategy planning."
      },
      {
        icon: <Hammer className="w-5 h-5 text-[#ef4d23]" />,
        title: "2. Prohibited Conduct",
        text: "You are strictly forbidden from: (a) Exploiting API architectures or executing reverse-engineering audits on our proprietary model logic. (b) Deploying excessive bot pools to spam our active backend endpoints. (c) Uploading compromised materials containing malware, ransomware, or trojans. (d) Engaging in illegal activities violating state regulations."
      },
      {
        icon: <AlertTriangle className="w-5 h-5 text-[#ef4d23]" />,
        title: "3. Liability Disclaimer",
        text: "All evaluations, failure rate forecasts, SWOT maps, and competitor matrix charts generated by Convix AI are statistical projections based on public indices. They serve as supplementary inputs for strategic planning and must never be interpreted as financial or legal counseling. Final capital allocations are entirely the founder's responsibility."
      },
      {
        icon: <HelpCircle className="w-5 h-5 text-[#ef4d23]" />,
        title: "4. Subscription Billing & Cancellations",
        text: "Certain features like deep-dive strategic pipelines require active payment cycles. You are free to cancel your active subscriptions at any time via your billing dashboard. Previously completed cycles are non-refundable retrospectively except under legal constraints."
      }
    ],
    contactTitle: "Get in Touch",
    contactText: "If you have any questions or require clarifications regarding these terms, contact our support team at:",
    footerText: "Thank you for building your next venture with Convix Idea Lab."
  };

  const t = locale === 'id' ? idContent : enContent;

  return (
    <div className="min-h-screen flex flex-col theme-transition" style={{ backgroundColor: 'var(--bg)', color: 'var(--fg)' }}>
      {/* ===== Header Hero Section ===== */}
      <section className="relative overflow-hidden pt-36 pb-20 border-b theme-transition" style={{ borderColor: 'var(--border)' }}>
        <div className="absolute inset-0 pointer-events-none opacity-20">
          <div className="absolute top-0 left-1/4 w-[1px] h-full theme-transition" style={{ backgroundColor: 'var(--border)' }} />
          <div className="absolute top-0 left-3/4 w-[1px] h-full theme-transition" style={{ backgroundColor: 'var(--border)' }} />
        </div>

        <div className="max-w-4xl mx-auto px-6 relative z-10 text-center">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={standardTransition}
          >
            <span className="text-[11px] font-mono font-bold tracking-widest text-[#ef4d23] bg-[#ef4d23]/[0.06] px-3 py-1.5 rounded-full border border-[#ef4d23]/10 uppercase mb-4 inline-block">
              Legal & Terms
            </span>
            <h1 className="text-3xl md:text-5xl font-medium tracking-tight mb-4 text-center theme-transition" style={{ color: 'var(--fg)' }}>
              {t.title}
            </h1>
            <p className="text-sm md:text-base leading-relaxed max-w-xl mx-auto theme-transition" style={{ color: 'var(--fg-secondary)' }}>
              {t.subtitle}
            </p>
            <span className="text-[11px] font-mono block mt-4 theme-transition" style={{ color: 'var(--fg-muted)' }}>
              {t.lastUpdated}
            </span>
          </motion.div>
        </div>
      </section>

      {/* ===== Terms Core Content ===== */}
      <section className="py-20 flex-1 theme-transition">
        <div className="max-w-3xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={standardTransition}
            className="mb-16 p-6 rounded-2xl border text-sm leading-relaxed theme-transition"
            style={{ backgroundColor: 'var(--bg-card)', borderColor: 'var(--border)' }}
          >
            <p className="theme-transition" style={{ color: 'var(--fg-secondary)' }}>{t.intro}</p>
          </motion.div>

          <div className="space-y-12">
            {t.sections.map((section, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: idx * 0.08 }}
                className="flex gap-5"
              >
                <div className="w-10 h-10 rounded-xl bg-[#ef4d23]/10 border border-[#ef4d23]/20 flex items-center justify-center shrink-0 mt-0.5">
                  {section.icon}
                </div>
                <div>
                  <h3 className="text-lg font-bold mb-3 theme-transition" style={{ color: 'var(--fg)' }}>{section.title}</h3>
                  <p className="text-[14px] leading-relaxed theme-transition" style={{ color: 'var(--fg-secondary)' }}>{section.text}</p>
                </div>
              </motion.div>
            ))}
          </div>

          {/* ===== Contact Block ===== */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={standardTransition}
            className="mt-20 p-8 rounded-3xl border text-center theme-transition"
            style={{ backgroundColor: 'var(--bg-elevated)', borderColor: 'var(--border)' }}
          >
            <h3 className="text-xl font-bold mb-3 theme-transition" style={{ color: 'var(--fg)' }}>{t.contactTitle}</h3>
            <p className="text-sm leading-relaxed mb-6 max-w-lg mx-auto theme-transition" style={{ color: 'var(--fg-secondary)' }}>
              {t.contactText}
            </p>
            <a
              href="mailto:arieffajarmarhas@gmail.com"
              className="inline-flex items-center gap-2 bg-[#ef4d23] text-white font-semibold text-sm px-6 py-3 rounded-full hover:bg-[#d9441f] transition-colors"
            >
              <Mail size={16} />
              arieffajarmarhas@gmail.com
            </a>
          </motion.div>

          <p className="text-center text-xs mt-16 theme-transition" style={{ color: 'var(--fg-muted)' }}>
            {t.footerText}
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
}
